### ISSUE TITLE
Request aborted when trying to use `res.dowload`

### ISSUE THREAD

**Issue by fbritoferreira** [evertdespiegeleer/zhttp#22]
Im trying to create a endpoint that download a zip file

```js
res.download(zipPath, zipName, (error) => {
                console.log('error', error);
            });
```

The file + file name exist and are valid but in the handler it doesnt seem to accept res.download as a valid way to end the request and the console.log throws this error

```sh
error Error: Request aborted
    at onaborted (/Users/fiferreira/code/roku/web-customer-care/web-cc-eng/ai/lodestar/node_modules/express/lib/response.js:1052:15)
    at Immediate._onImmediate (/Users/fiferreira/code/roku/web-customer-care/web-cc-eng/ai/lodestar/node_modules/express/lib/response.js:1094:9)
    at process.processImmediate (node:internal/timers:476:21) {
  code: 'ECONNABORTED'
}
```

**Comment by evertdespiegeleer** [comment]
[This stackoverflow anwser](https://stackoverflow.com/a/50995917) describes pretty well what's happening.
As Express only _kind of_ supports async logic, they export some function which do async-like stuff in an unconventional manner (callbacks that is; It was the way of doing async a while back, but better methods exist now).

`res.download` is essentially an asynchronous process, but it's technically not a JS async function. When you fire `res.download`, it does what it does and when it's ready, it calls `res.write` (or something similar) internally.
Problem: calling this function is just like calling `console.log('hey')`. We just assume that it instantly completes, so we continue with the logic that comes after that. The problem is that it does not instantly complete, but as it's not a JS async function, we can't know that.

The function does have a callback though, which we can use to _promisify_ it:

```ts
downloadController.endpoint(
  get('/download', 'downloadThatZipFile')
    .handler(async (input, req: Request, res: Response) => {
      await new Promise((resolve, reject) => {
        res.download(pathToZipFile, 'name.zip', err => {
          if (err != null) resolve(err)
          reject(err)
        })
      })
    })
)
```

Tested it, seems to work :)
